
export const FETCH_PRODUCT = 'FETCH_PRODUCT'

export const ADD_PRODUCT = 'ADD_PRODUCT'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const GET_PRODUCT = 'GET_PRODUCT'

export const FETCH_ANIMAL = 'FETCH_ANIMAL'

export const GET_ANIMAL = 'ADD_ANIMAL'


export const ADD_TO_CART = 'ADD_TO_CART'

export const DELETE_ITEM_CART = 'DELETE_ITEM_CART'

export const UPDATE_NUMBER_ITEM = 'UPDATE_NUMBER_ITEM'
